import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
//import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryProvider } from "@/react-query-provider";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { Breadcrumb } from "@/components/layout/breadcrumb";
import UserNav from "@/components/layout/user-nav";
import { Input } from "@/components/ui/input";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ReactQueryProvider>
          <NuqsAdapter>
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full">
                <div className="flex justify-between p-3  border-b">
                  <div className="flex gap-2 items-center">
                    <SidebarTrigger />
                    <Breadcrumb />
                  </div>
                  <div className="flex gap-2">
                    <Input placeholder="Search" />
                    <UserNav />
                  </div>
                </div>
                <div className="p-3">{children}</div>
              </main>
            </SidebarProvider>

            <Toaster />
          </NuqsAdapter>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
